// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.4
// source: initialition.proto

package initialition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntegralType  string                 `protobuf:"bytes,1,opt,name=integral_type,json=integralType,proto3" json:"integral_type,omitempty"`
	Integral      string                 `protobuf:"bytes,2,opt,name=integral,proto3" json:"integral,omitempty"`
	Bak           string                 `protobuf:"bytes,3,opt,name=bak,proto3" json:"bak,omitempty"`
	OperationTime string                 `protobuf:"bytes,4,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationRequest) Reset() {
	*x = IntegrationRequest{}
	mi := &file_initialition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationRequest) ProtoMessage() {}

func (x *IntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_initialition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationRequest.ProtoReflect.Descriptor instead.
func (*IntegrationRequest) Descriptor() ([]byte, []int) {
	return file_initialition_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrationRequest) GetIntegralType() string {
	if x != nil {
		return x.IntegralType
	}
	return ""
}

func (x *IntegrationRequest) GetIntegral() string {
	if x != nil {
		return x.Integral
	}
	return ""
}

func (x *IntegrationRequest) GetBak() string {
	if x != nil {
		return x.Bak
	}
	return ""
}

func (x *IntegrationRequest) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

func (x *IntegrationRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type IntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bigint        int64                  `protobuf:"varint,1,opt,name=bigint,proto3" json:"bigint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationResponse) Reset() {
	*x = IntegrationResponse{}
	mi := &file_initialition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationResponse) ProtoMessage() {}

func (x *IntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_initialition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationResponse.ProtoReflect.Descriptor instead.
func (*IntegrationResponse) Descriptor() ([]byte, []int) {
	return file_initialition_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationResponse) GetBigint() int64 {
	if x != nil {
		return x.Bigint
	}
	return 0
}

var File_initialition_proto protoreflect.FileDescriptor

var file_initialition_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0xaf,
	0x01, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x61, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x2d, 0x0a, 0x13, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x67, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x32,
	0x56, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x0b,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_initialition_proto_rawDescOnce sync.Once
	file_initialition_proto_rawDescData []byte
)

func file_initialition_proto_rawDescGZIP() []byte {
	file_initialition_proto_rawDescOnce.Do(func() {
		file_initialition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_initialition_proto_rawDesc), len(file_initialition_proto_rawDesc)))
	})
	return file_initialition_proto_rawDescData
}

var file_initialition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_initialition_proto_goTypes = []any{
	(*IntegrationRequest)(nil),  // 0: template.IntegrationRequest
	(*IntegrationResponse)(nil), // 1: template.IntegrationResponse
}
var file_initialition_proto_depIdxs = []int32{
	0, // 0: template.Integrate.Integration:input_type -> template.IntegrationRequest
	0, // 1: template.Integrate.Integration:output_type -> template.IntegrationRequest
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_initialition_proto_init() }
func file_initialition_proto_init() {
	if File_initialition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_initialition_proto_rawDesc), len(file_initialition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_initialition_proto_goTypes,
		DependencyIndexes: file_initialition_proto_depIdxs,
		MessageInfos:      file_initialition_proto_msgTypes,
	}.Build()
	File_initialition_proto = out.File
	file_initialition_proto_goTypes = nil
	file_initialition_proto_depIdxs = nil
}
