// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: user_enter.proto

package user_enter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UserEnter_AddUserEnter_FullMethodName = "/user_enter.UserEnter/AddUserEnter"
)

// UserEnterClient is the client API for UserEnter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserEnterClient interface {
	AddUserEnter(ctx context.Context, in *AddUserEnterRequest, opts ...grpc.CallOption) (*AddUserEnterResponse, error)
}

type userEnterClient struct {
	cc grpc.ClientConnInterface
}

func NewUserEnterClient(cc grpc.ClientConnInterface) UserEnterClient {
	return &userEnterClient{cc}
}

func (c *userEnterClient) AddUserEnter(ctx context.Context, in *AddUserEnterRequest, opts ...grpc.CallOption) (*AddUserEnterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserEnterResponse)
	err := c.cc.Invoke(ctx, UserEnter_AddUserEnter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserEnterServer is the server API for UserEnter service.
// All implementations must embed UnimplementedUserEnterServer
// for forward compatibility
type UserEnterServer interface {
	AddUserEnter(context.Context, *AddUserEnterRequest) (*AddUserEnterResponse, error)
	mustEmbedUnimplementedUserEnterServer()
}

// UnimplementedUserEnterServer must be embedded to have forward compatible implementations.
type UnimplementedUserEnterServer struct {
}

func (UnimplementedUserEnterServer) AddUserEnter(context.Context, *AddUserEnterRequest) (*AddUserEnterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserEnter not implemented")
}
func (UnimplementedUserEnterServer) mustEmbedUnimplementedUserEnterServer() {}

// UnsafeUserEnterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserEnterServer will
// result in compilation errors.
type UnsafeUserEnterServer interface {
	mustEmbedUnimplementedUserEnterServer()
}

func RegisterUserEnterServer(s grpc.ServiceRegistrar, srv UserEnterServer) {
	s.RegisterService(&UserEnter_ServiceDesc, srv)
}

func _UserEnter_AddUserEnter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserEnterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserEnterServer).AddUserEnter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserEnter_AddUserEnter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserEnterServer).AddUserEnter(ctx, req.(*AddUserEnterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserEnter_ServiceDesc is the grpc.ServiceDesc for UserEnter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserEnter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_enter.UserEnter",
	HandlerType: (*UserEnterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserEnter",
			Handler:    _UserEnter_AddUserEnter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_enter.proto",
}
