// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: user_enter.proto

package user_enter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserEnterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          uint64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Province     string `protobuf:"bytes,2,opt,name=Province,proto3" json:"Province,omitempty"`
	City         string `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	District     string `protobuf:"bytes,4,opt,name=District,proto3" json:"District,omitempty"`
	Address      string `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	MerchantName string `protobuf:"bytes,6,opt,name=MerchantName,proto3" json:"MerchantName,omitempty"`
	LinkTel      string `protobuf:"bytes,7,opt,name=LinkTel,proto3" json:"LinkTel,omitempty"`
	Charter      string `protobuf:"bytes,8,opt,name=Charter,proto3" json:"Charter,omitempty"`
}

func (x *AddUserEnterRequest) Reset() {
	*x = AddUserEnterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_enter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserEnterRequest) ProtoMessage() {}

func (x *AddUserEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_enter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserEnterRequest.ProtoReflect.Descriptor instead.
func (*AddUserEnterRequest) Descriptor() ([]byte, []int) {
	return file_user_enter_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserEnterRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddUserEnterRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddUserEnterRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddUserEnterRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddUserEnterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddUserEnterRequest) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *AddUserEnterRequest) GetLinkTel() string {
	if x != nil {
		return x.LinkTel
	}
	return ""
}

func (x *AddUserEnterRequest) GetCharter() string {
	if x != nil {
		return x.Charter
	}
	return ""
}

type AddUserEnterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserEnterId uint64 `protobuf:"varint,1,opt,name=UserEnterId,proto3" json:"UserEnterId,omitempty"`
}

func (x *AddUserEnterResponse) Reset() {
	*x = AddUserEnterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_enter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserEnterResponse) ProtoMessage() {}

func (x *AddUserEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_enter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserEnterResponse.ProtoReflect.Descriptor instead.
func (*AddUserEnterResponse) Descriptor() ([]byte, []int) {
	return file_user_enter_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserEnterResponse) GetUserEnterId() uint64 {
	if x != nil {
		return x.UserEnterId
	}
	return 0
}

var File_user_enter_proto protoreflect.FileDescriptor

var file_user_enter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x22, 0xe5,
	0x01, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x65, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x68, 0x61, 0x72, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x32, 0x5e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x51, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_enter_proto_rawDescOnce sync.Once
	file_user_enter_proto_rawDescData = file_user_enter_proto_rawDesc
)

func file_user_enter_proto_rawDescGZIP() []byte {
	file_user_enter_proto_rawDescOnce.Do(func() {
		file_user_enter_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_enter_proto_rawDescData)
	})
	return file_user_enter_proto_rawDescData
}

var file_user_enter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_enter_proto_goTypes = []any{
	(*AddUserEnterRequest)(nil),  // 0: user_enter.AddUserEnterRequest
	(*AddUserEnterResponse)(nil), // 1: user_enter.AddUserEnterResponse
}
var file_user_enter_proto_depIdxs = []int32{
	0, // 0: user_enter.UserEnter.AddUserEnter:input_type -> user_enter.AddUserEnterRequest
	1, // 1: user_enter.UserEnter.AddUserEnter:output_type -> user_enter.AddUserEnterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enter_proto_init() }
func file_user_enter_proto_init() {
	if File_user_enter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_enter_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserEnterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_enter_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddUserEnterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_enter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_enter_proto_goTypes,
		DependencyIndexes: file_user_enter_proto_depIdxs,
		MessageInfos:      file_user_enter_proto_msgTypes,
	}.Build()
	File_user_enter_proto = out.File
	file_user_enter_proto_rawDesc = nil
	file_user_enter_proto_goTypes = nil
	file_user_enter_proto_depIdxs = nil
}
