// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: store_cart.proto

package store_cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddStoreCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid               uint64 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Type              string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	ProductId         uint64 `protobuf:"varint,3,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	ProductAttrUnique string `protobuf:"bytes,4,opt,name=ProductAttrUnique,proto3" json:"ProductAttrUnique,omitempty"`
	CartNum           uint64 `protobuf:"varint,5,opt,name=CartNum,proto3" json:"CartNum,omitempty"`
}

func (x *AddStoreCartRequest) Reset() {
	*x = AddStoreCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStoreCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStoreCartRequest) ProtoMessage() {}

func (x *AddStoreCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStoreCartRequest.ProtoReflect.Descriptor instead.
func (*AddStoreCartRequest) Descriptor() ([]byte, []int) {
	return file_store_cart_proto_rawDescGZIP(), []int{0}
}

func (x *AddStoreCartRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddStoreCartRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddStoreCartRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddStoreCartRequest) GetProductAttrUnique() string {
	if x != nil {
		return x.ProductAttrUnique
	}
	return ""
}

func (x *AddStoreCartRequest) GetCartNum() uint64 {
	if x != nil {
		return x.CartNum
	}
	return 0
}

type AddStoreCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreCartId uint64 `protobuf:"varint,1,opt,name=StoreCartId,proto3" json:"StoreCartId,omitempty"`
}

func (x *AddStoreCartResponse) Reset() {
	*x = AddStoreCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStoreCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStoreCartResponse) ProtoMessage() {}

func (x *AddStoreCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStoreCartResponse.ProtoReflect.Descriptor instead.
func (*AddStoreCartResponse) Descriptor() ([]byte, []int) {
	return file_store_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddStoreCartResponse) GetStoreCartId() uint64 {
	if x != nil {
		return x.StoreCartId
	}
	return 0
}

var File_store_cart_proto protoreflect.FileDescriptor

var file_store_cart_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x22, 0xa1,
	0x01, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x74,
	0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x43, 0x61, 0x72, 0x74, 0x4e,
	0x75, 0x6d, 0x22, 0x38, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x43, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x72, 0x74, 0x49, 0x64, 0x32, 0x5e, 0x0a, 0x09,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x72, 0x74, 0x12, 0x51, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x3b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_cart_proto_rawDescOnce sync.Once
	file_store_cart_proto_rawDescData = file_store_cart_proto_rawDesc
)

func file_store_cart_proto_rawDescGZIP() []byte {
	file_store_cart_proto_rawDescOnce.Do(func() {
		file_store_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_cart_proto_rawDescData)
	})
	return file_store_cart_proto_rawDescData
}

var file_store_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_store_cart_proto_goTypes = []any{
	(*AddStoreCartRequest)(nil),  // 0: store_cart.AddStoreCartRequest
	(*AddStoreCartResponse)(nil), // 1: store_cart.AddStoreCartResponse
}
var file_store_cart_proto_depIdxs = []int32{
	0, // 0: store_cart.StoreCart.AddStoreCart:input_type -> store_cart.AddStoreCartRequest
	1, // 1: store_cart.StoreCart.AddStoreCart:output_type -> store_cart.AddStoreCartResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_cart_proto_init() }
func file_store_cart_proto_init() {
	if File_store_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_cart_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddStoreCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_cart_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddStoreCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_cart_proto_goTypes,
		DependencyIndexes: file_store_cart_proto_depIdxs,
		MessageInfos:      file_store_cart_proto_msgTypes,
	}.Build()
	File_store_cart_proto = out.File
	file_store_cart_proto_rawDesc = nil
	file_store_cart_proto_goTypes = nil
	file_store_cart_proto_depIdxs = nil
}
